---
detectors:

  LongParameterList:
    max_params: 6

  TooManyStatements:
    max_statements: 10

  TooManyInstanceVariables:
    max_instance_variables: 5

  UncommunicativeModuleName:
    accept:
    - B64
