AllCops:
  NewCops: enable
  Exclude:
  - bin/*
  - pkg/*
  - tmp/**/*
  - lib/*/version.rb
  - spec/spec_helper.rb
  - Gemfile
  - '*.gemspec'
  - Rakefile
  - .simplecov

Metrics/BlockLength:
  Exclude:
  - 'spec/**/*'

Metrics/CyclomaticComplexity:
  Max: 7

Layout/LineLength:
  Max: 110

Metrics/MethodLength:
  Max: 15

Metrics/ParameterLists:
  Max: 6
