AllCops:
  Exclude:
  - bin/*
  - pkg/*
  - tmp/**/*
  - lib/*/version.rb
  - spec/spec_helper.rb
  - Gemfile
  - '*.gemspec'
  - Rakefile

Metrics/BlockLength:
  Exclude:
  - 'spec/**/*'

Metrics/CyclomaticComplexity:
  Max: 7

Metrics/LineLength:
  Max: 110

Metrics/MethodLength:
  Max: 15

Metrics/ParameterLists:
  Max: 6
